In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from session15 import get_session15_endomaps, make_presentation

In [2]:
XG,YG = get_session15_endomaps()


In [3]:
XM = nx.adjacency_matrix(XG)


In [4]:
np.all([True,True,True,False])

False

In [5]:
def find_cycle_from_matrix(M,v=None):
    my_vec = v if v is not None else np.full((M.shape[0],),1)
    powers_of_M = [my_vec]
    i = 0
    next_power = M
    while np.all(list(map(lambda x: np.any(my_vec @ next_power != x),powers_of_M))):
        i += 1
        powers_of_M.append(my_vec @ next_power)
        next_power = next_power @ M
    incident_at = list(map(lambda x: np.any(my_vec @ next_power != x),powers_of_M)).index(False)
    num_steps = len(powers_of_M)
    powers_of_M.append(my_vec @ next_power)
    return powers_of_M, num_steps-incident_at
        
find_cycle_from_matrix(XM)

([array([1, 1, 1, 1, 1, 1, 1, 1, 1]),
  array([0, 0, 0, 1, 1, 3, 2, 1, 1], dtype=int32),
  array([0, 0, 0, 1, 0, 2, 3, 2, 1], dtype=int32),
  array([0, 0, 0, 1, 0, 2, 2, 3, 1], dtype=int32),
  array([0, 0, 0, 1, 0, 3, 2, 2, 1], dtype=int32),
  array([0, 0, 0, 1, 0, 2, 3, 2, 1], dtype=int32)],
 3)

In [6]:
YM = nx.adjacency_matrix(YG)
find_cycle_from_matrix(YM)

([array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
  array([0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0], dtype=int32),
  array([0, 0, 0, 1, 3, 2, 1, 1, 1, 2, 1, 1, 0], dtype=int32),
  array([0, 0, 0, 1, 1, 3, 2, 1, 1, 1, 2, 1, 0], dtype=int32),
  array([0, 0, 0, 2, 1, 1, 3, 1, 1, 1, 1, 2, 0], dtype=int32),
  array([0, 0, 0, 3, 2, 1, 1, 1, 1, 2, 1, 1, 0], dtype=int32),
  array([0, 0, 0, 1, 3, 2, 1, 1, 1, 1, 2, 1, 0], dtype=int32),
  array([0, 0, 0, 1, 1, 3, 2, 1, 1, 1, 1, 2, 0], dtype=int32),
  array([0, 0, 0, 2, 1, 1, 3, 1, 1, 2, 1, 1, 0], dtype=int32),
  array([0, 0, 0, 3, 2, 1, 1, 1, 1, 1, 2, 1, 0], dtype=int32),
  array([0, 0, 0, 1, 3, 2, 1, 1, 1, 1, 1, 2, 0], dtype=int32),
  array([0, 0, 0, 1, 1, 3, 2, 1, 1, 2, 1, 1, 0], dtype=int32),
  array([0, 0, 0, 2, 1, 1, 3, 1, 1, 1, 2, 1, 0], dtype=int32),
  array([0, 0, 0, 3, 2, 1, 1, 1, 1, 1, 1, 2, 0], dtype=int32),
  array([0, 0, 0, 1, 3, 2, 1, 1, 1, 2, 1, 1, 0], dtype=int32)],
 12)

In [7]:
PRIME_NUMBERS = [2]

In [8]:
list(map(lambda x: 3 % x != 0,PRIME_NUMBERS))

[True]

In [9]:
PRIME_NUMBERS = [2]

def prime_number_by_index(n):
    global PRIME_NUMBERS
    while n >= len(PRIME_NUMBERS):
        # sieve next prime
        p_n = PRIME_NUMBERS[-1]+1
        while not np.all(list(map(lambda x: p_n % x != 0,PRIME_NUMBERS))):
            p_n += 1
        PRIME_NUMBERS.append(p_n)
    return PRIME_NUMBERS[n]
    
        

In [10]:
list(map(prime_number_by_index,range(15)))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

In [11]:
from functools import reduce
def power_of_primes_map(v):
    size = len(v)
    prime_vec = map(prime_number_by_index,range(size))
    powers = [p**v[i] for i,p in enumerate(prime_vec)]
    return reduce(lambda x, y: x*y, powers) if len(powers) else 0

power_of_primes_map([0, 2, 1])

45

In [12]:
power_of_primes_map([0,0,0,0,0])

1

In [13]:
power_of_primes_map([])

0

In [14]:
def modular_division(n,p):
    i = 1
    power = p
    modulo = n%power
    while power < n and modulo == 0:
        i += 1
        power *= p
        modulo = n%power
    return i if modulo == 0 else i-1

modular_division(40,2)

3

In [15]:
def prime_factorization(n):
    i = 0
    prime_powers = []
    next_prime = prime_number_by_index(i)
    while n >= next_prime:
        #print(f"Checking {n} for divisibility by {next_prime}")
        div_res = modular_division(n,next_prime)
        prime_powers.append(div_res)
        if div_res > 0:
            n = int(n/(next_prime**div_res))
        i += 1
        next_prime = prime_number_by_index(i)
    return prime_powers

prime_factorization(56)

[3, 0, 0, 1]

In [16]:
list(map(prime_factorization,range(10)))

[[], [], [1], [0, 1], [2], [0, 0, 1], [1, 1], [0, 0, 0, 1], [3], [0, 2]]

In [17]:
list(map(len,map(prime_factorization,range(10))))

[0, 0, 1, 2, 1, 3, 2, 4, 1, 2]

In [18]:
X_cycle,X_cycle_length = find_cycle_from_matrix(XM)
print(X_cycle)
print(X_cycle_length)


[array([1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 0, 0, 1, 1, 3, 2, 1, 1], dtype=int32), array([0, 0, 0, 1, 0, 2, 3, 2, 1], dtype=int32), array([0, 0, 0, 1, 0, 2, 2, 3, 1], dtype=int32), array([0, 0, 0, 1, 0, 3, 2, 2, 1], dtype=int32), array([0, 0, 0, 1, 0, 2, 3, 2, 1], dtype=int32)]
3


In [19]:
Y_cycle,Y_cycle_length = find_cycle_from_matrix(YM)
print(Y_cycle)
print(Y_cycle_length)

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0], dtype=int32), array([0, 0, 0, 1, 3, 2, 1, 1, 1, 2, 1, 1, 0], dtype=int32), array([0, 0, 0, 1, 1, 3, 2, 1, 1, 1, 2, 1, 0], dtype=int32), array([0, 0, 0, 2, 1, 1, 3, 1, 1, 1, 1, 2, 0], dtype=int32), array([0, 0, 0, 3, 2, 1, 1, 1, 1, 2, 1, 1, 0], dtype=int32), array([0, 0, 0, 1, 3, 2, 1, 1, 1, 1, 2, 1, 0], dtype=int32), array([0, 0, 0, 1, 1, 3, 2, 1, 1, 1, 1, 2, 0], dtype=int32), array([0, 0, 0, 2, 1, 1, 3, 1, 1, 2, 1, 1, 0], dtype=int32), array([0, 0, 0, 3, 2, 1, 1, 1, 1, 1, 2, 1, 0], dtype=int32), array([0, 0, 0, 1, 3, 2, 1, 1, 1, 1, 1, 2, 0], dtype=int32), array([0, 0, 0, 1, 1, 3, 2, 1, 1, 2, 1, 1, 0], dtype=int32), array([0, 0, 0, 2, 1, 1, 3, 1, 1, 1, 2, 1, 0], dtype=int32), array([0, 0, 0, 3, 2, 1, 1, 1, 1, 1, 1, 2, 0], dtype=int32), array([0, 0, 0, 1, 3, 2, 1, 1, 1, 2, 1, 1, 0], dtype=int32)]
12


In [20]:
def make_one_hot(size,idx):
    assert idx < size
    return [1 if i == idx else 0 for i in range(size)]
make_one_hot(5,3)


[0, 0, 0, 1, 0]

In [21]:
def find_all_cycles_from_matrix(M):
    size = M.shape[0]
    cycles_by_length = {}
    for i in range(size):
        one_hot = make_one_hot(size,i)
        print(one_hot)
        cycle,cycle_length = find_cycle_from_matrix(M,one_hot)
        print(f"found cycle of length {cycle_length}:\n\t{cycle}")
        old_cycle_list = cycles_by_length[cycle_length] if cycle_length in cycles_by_length else []
        cycles_by_length[cycle_length] = old_cycle_list+[(i,cycle)]
    return cycles_by_length

In [22]:
X_cycles = find_all_cycles_from_matrix(XM)
print(X_cycles)

[1, 0, 0, 0, 0, 0, 0, 0, 0]
found cycle of length 3:
	[[1, 0, 0, 0, 0, 0, 0, 0, 0], array([0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32), array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32)]
[0, 1, 0, 0, 0, 0, 0, 0, 0]
found cycle of length 3:
	[[0, 1, 0, 0, 0, 0, 0, 0, 0], array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32), array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32)]
[0, 0, 1, 0, 0, 0, 0, 0, 0]
found cycle of length 3:
	[[0, 0, 1, 0, 0, 0, 0, 0, 0], array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32), array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32)]
[0, 0, 0, 1, 0, 0, 0, 0, 0]
found cycle of length 2:
	[[0, 0, 0, 1, 0, 0, 0, 0, 0], array([0, 0, 0, 0, 0, 0, 0,

In [23]:
Y_cycles = find_all_cycles_from_matrix(YM)
print(Y_cycles)

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
found cycle of length 4:
	[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
found cycle of length 4:
	[[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)]
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
found cycle 

In [24]:
X_pres = make_presentation(XG)
print(X_pres)
Y_pres = make_presentation(YG)
print(Y_pres)


{'generators': ['X0', 'X1', 'X2', 'X3'], 'relations': [(('X0', 5), ('X0', 2)), (('X1', 1), ('X0', 2)), (('X2', 1), ('X0', 3)), (('X3', 2), ('X3', 0))]}
{'generators': ['Yp', 'Yq', 'Yz', 'Ym'], 'relations': [(('Yp', 6), ('Yp', 2)), (('Yq', 1), ('Yp', 1)), (('Yz', 4), ('Yz', 1)), (('Ym', 2), ('Ym', 0))]}


In [25]:
def map_N_to_Generators(pres):
    names = {g:i for i,g in enumerate(pres['generators'])}
    return {
        'generators':list(map(lambda x: names[x],pres['generators'])),
        'relations':list(map(lambda x: ((names[x[0][0]],x[0][1]),(names[x[1][0]],x[1][1])),pres['relations'])),
        'retraction':names
    }
X_pres_N = map_N_to_Generators(X_pres)
print(X_pres_N)

{'generators': [0, 1, 2, 3], 'relations': [((0, 5), (0, 2)), ((1, 1), (0, 2)), ((2, 1), (0, 3)), ((3, 2), (3, 0))], 'retraction': {'X0': 0, 'X1': 1, 'X2': 2, 'X3': 3}}


In [26]:
Y_pres_N = map_N_to_Generators(Y_pres)
print(Y_pres_N)

{'generators': [0, 1, 2, 3], 'relations': [((0, 6), (0, 2)), ((1, 1), (0, 1)), ((2, 4), (2, 1)), ((3, 2), (3, 0))], 'retraction': {'Yp': 0, 'Yq': 1, 'Yz': 2, 'Ym': 3}}


In [27]:
# for each generator, I want to know what relations it's referenced in
def relations_by_generator(relations,gen):
    return list(filter(lambda x: x[0][0] == gen or x[1][0] == gen,relations))
[relations_by_generator(X_pres_N["relations"],i) for i in X_pres_N["generators"]]


[[((0, 5), (0, 2)), ((1, 1), (0, 2)), ((2, 1), (0, 3))],
 [((1, 1), (0, 2))],
 [((2, 1), (0, 3))],
 [((3, 2), (3, 0))]]

In [28]:
[relations_by_generator(Y_pres_N["relations"],i) for i in Y_pres_N["generators"]]

[[((0, 6), (0, 2)), ((1, 1), (0, 1))],
 [((1, 1), (0, 1))],
 [((2, 4), (2, 1))],
 [((3, 2), (3, 0))]]

In [29]:
X_cycles

{3: [(0,
   [[1, 0, 0, 0, 0, 0, 0, 0, 0],
    array([0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32)]),
  (1,
   [[0, 1, 0, 0, 0, 0, 0, 0, 0],
    array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32)]),
  (2,
   [[0, 0, 1, 0, 0, 0, 0, 0, 0],
    array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32)]),
  (4,
   [[0, 0, 0, 0, 1, 0, 0, 0, 0],
    array([0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int32),
    array([0, 0, 0, 0, 0, 0, 0, 1, 0], d

In [30]:
from session15 import zig_zag, reverse_zig_zag

# lets test out a new bijection N <--> N x N
# based on the property that each n>=1, n = 2^i*(2*j+1)
# for a unique pair i,j since each n has a unique
# prime factorization 

def N_x_N_to_N(p):
    return 2**(p[0])*(2*p[1]+1)-1
# check how this matches up with previous version   
sorted(list(map(lambda x: (N_x_N_to_N(x),x),zig_zag(10))))

[(0, (0, 0)),
 (1, (1, 0)),
 (2, (0, 1)),
 (3, (2, 0)),
 (4, (0, 2)),
 (5, (1, 1)),
 (6, (0, 3)),
 (7, (3, 0)),
 (9, (1, 2)),
 (11, (2, 1))]

In [31]:
# now lets write the inverse
def N_to_N_x_N(n):
    m = n+1
    i = m % 2
    log_2 = 0
    while i == 0 and m > 0:
        m = int(m/2)
        log_2 += 1
        i = m % 2
    return (log_2,int((m-i)/2))
list(zip(map(N_to_N_x_N,range(10)),range(10)))

[((0, 0), 0),
 ((1, 0), 1),
 ((0, 1), 2),
 ((2, 0), 3),
 ((0, 2), 4),
 ((1, 1), 5),
 ((0, 3), 6),
 ((3, 0), 7),
 ((0, 4), 8),
 ((1, 2), 9)]

In [32]:
# now lets compare them to check
list(map(N_x_N_to_N,list(map(N_to_N_x_N,range(10)))))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
def uplift_relation(r):
    r_0 = N_x_N_to_N(r[0])
    print(f"{r[0]} -> {r_0}")
    r_1 = N_x_N_to_N(r[1])
    print(f"{r[1]} -> {r_1}")
    r_2 = N_x_N_to_N((r_0,r_1))
    print(f"\t -> {r_2}")
    return r_2

In [34]:
uplift_relation(X_pres_N['relations'][0])

(0, 5) -> 10
(0, 2) -> 4
	 -> 9215


9215

In [35]:
X_rel_N = [uplift_relation(r) for r in X_pres_N['relations']]

(0, 5) -> 10
(0, 2) -> 4
	 -> 9215
(1, 1) -> 5
(0, 2) -> 4
	 -> 287
(2, 1) -> 11
(0, 3) -> 6
	 -> 26623
(3, 2) -> 39
(3, 0) -> 7
	 -> 8246337208319


In [36]:
Y_rel_N = [uplift_relation(r) for r in Y_pres_N['relations']]

(0, 6) -> 12
(0, 2) -> 4
	 -> 36863
(1, 1) -> 5
(0, 1) -> 2
	 -> 159
(2, 4) -> 35
(2, 1) -> 11
	 -> 790273982463
(3, 2) -> 39
(3, 0) -> 7
	 -> 8246337208319


In [37]:
incidence = list(set(X_rel_N).intersection(set(Y_rel_N)))
print(incidence)

[8246337208319]


In [38]:
p1 = N_to_N_x_N(incidence[0])
print(p1)

(39, 7)


In [39]:
p2 = (N_to_N_x_N(p1[0]),N_to_N_x_N(p1[1]))
print(p2)

((3, 2), (3, 0))


In [40]:
# lets try removing that intersection and repeating the process
X_rel_N.remove(incidence[0])

In [41]:
Y_rel_N.remove(incidence[0])

In [42]:
print(X_rel_N)
print(Y_rel_N)

[9215, 287, 26623]
[36863, 159, 790273982463]


In [43]:
X_rel_N2 = [N_x_N_to_N((i,X_rel_N[i]))for i in range(3)]
print(X_rel_N2)

[18430, 1149, 212987]


In [44]:
set([lambda x:x])

{<function __main__.<lambda>(x)>}

In [45]:

def compose_maps(A,B):
    return {k:B[v] for k,v in zip(A.keys(),A.values())}

compose_maps({0:0},{0:1})

{0: 1}

In [46]:
all([True,False])

False

In [49]:
try:
    set([[],[0],[0,1]])
    print("shouldn't hit this")
except TypeError as e:
    print(f"Error: {e}")

Error: unhashable type: 'list'


In [50]:
def force_set(L):
    try:
        return set(L)
    except TypeError:
        return set(list(map(str,L)))
        

In [51]:
force_set([[],[0],[0,1]])

{'[0, 1]', '[0]', '[]'}

In [52]:
import categories

1 from |[0]|=1  to |[0]|=1
2 from |[0]|=1  to |[0, 1]|=2
1 from |[0, 1]|=2  to |[0]|=1
4 from |[0, 1]|=2  to |[0, 1]|=2
